name: PR Workflow by ${{ github.actor }}

on:
  pull_request:

env:
  GITHUB_ACTIONS: "true"

jobs:
  github-task-job:
    runs-on: ubuntu-latest

    steps:
      - name: Show GITHUB_ACTIONS environment variable
        run: echo "GITHUB_ACTIONS is set to $GITHUB_ACTIONS"

      - name: Show branch and repository name
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Branch: ${{ github.head_ref }}"

      - name: Show triggering event
        run: echo "Triggered by event: ${{ github.event_name }}"
